### ISSUE TITLE
Add Tournament system into matches

### ISSUE THREAD

**Issue by zischler** [zhaw-web1/angular-app#77]
Matches are at the moment only good for BO1, BO3,... but not for whole tournaments.
It would be nice to have an option to fill in tournaments with it. One possibility would be to make more teams addable to a match and with that everything modular.
![image](https://user-images.githubusercontent.com/26481494/51856539-46847900-2330-11e9-820e-c85c8157e597.png)
Also the place and preview should be styled in another way. Change "VS" with "AT".

**Comment by cfi2017** [comment]
Could you post a design concept for how tournaments would look? I need to get a better idea of what I'm working with.

**Comment by zischler** [comment]
Will do that next week.

**Comment by zischler** [comment]
![match](https://user-images.githubusercontent.com/26481494/52229202-a8a32800-28b4-11e9-8f71-9966b253eefc.png)

**Comment by zischler** [comment]
So:
- Match maps have to be variable
- teams have to be variable
- Only one input for totalScore

**Comment by zischler** [comment]
We have to look at the data structure. Had some problems modeling it atm.
